import type { ParameterPreset } from "@/lib/types";

/** Fallback als MariaDB niet bereikbaar is */
export const STATIC_PRESETS: ParameterPreset[] = [
  {
    id: 1,
    slug: "normaal-long",
    label_nl: "Normaal – longcapilair",
    pH: 7.45,
    pCO2: 40,
    temp_c: 37,
    bpg_mmol: 4.5,
    context: "long",
    sort_order: 1,
  },
  {
    id: 2,
    slug: "normaal-weefsel",
    label_nl: "Normaal – weefselcapilair",
    pH: 7.35,
    pCO2: 46,
    temp_c: 37,
    bpg_mmol: 4.5,
    context: "weefsel",
    sort_order: 2,
  },
  {
    id: 3,
    slug: "copd",
    label_nl: "COPD – chronische hypercapnie",
    pH: 7.32,
    pCO2: 55,
    temp_c: 37,
    bpg_mmol: 5.0,
    context: "weefsel",
    sort_order: 3,
  },
  {
    id: 4,
    slug: "metabolische-alkalose",
    label_nl: "Metabolische alkalose",
    pH: 7.5,
    pCO2: 40,
    temp_c: 37,
    bpg_mmol: 4.5,
    context: "long",
    sort_order: 4,
  },
  {
    id: 5,
    slug: "inspanning",
    label_nl: "Inspannend weefsel",
    pH: 7.25,
    pCO2: 50,
    temp_c: 39,
    bpg_mmol: 4.0,
    context: "weefsel",
    sort_order: 5,
  },
];
